import enum


class EndpointID(enum.IntEnum):
    PING = 1
    PONG = 2

    LOGIN = 10  # Done
    LOGIN_RESULT = 11  # Done
    # LOGOUT = 12
    # LOGOUT_RESULT = 13

    # Logged in - Server wide updates
    ERROR_FULFILLING_SERVER_REQUEST = 19
    CREATE_PROJECT = 20  # Done
    DELETE_PROJECT = 30  # Done
    OPEN_PROJECT = 40
    RENAME_PROJECT = 50  # Done

    SYNC_PROJECT = 41

    CREATED_PROJECT = 22
    DELETED_PROJECT = 32
    OPENED_PROJECT = 42
    RENAMED_PROJECT = 52

    # Project wide updates
    ERROR_FULFILLING_PROJECT_REQUEST = 99
    JOIN_DOC = 100
    LEAVE_DOC = 110
    CREATE_DOC = 120
    DELETE_DOC = 130
    CREATE_FOLDER = 140

    SYNC_DOC = 101

    JOINED_DOC = 102
    LEFT_DOC = 112
    CREATED_DOC = 122
    DELETED_DOC = 132
    CREATED_FOLDER = 142

    # Doc wide updates
    ERROR_FULFILLING_DOC_UPDATES = 299
    ACQUIRE_BLOCK = 300
    RELEASE_BLOCK = 310
    UPDATE_BLOCK = 320
    ADD_BLOCK = 330
    REMOVE_BLOCK = 340
    SYNC_BLOCK_REQUEST = 350

    SYNC_BLOCK = 351

    ACQUIRED_BLOCK = 302
    RELEASED_BLOCK = 312
    UPDATED_BLOCK = 322
    BLOCK_ADDED = 332
    REMOVED_BLOCK = 342

    # User updates - Broadcast project wide
    ERROR_FULFILLING_USER_REQUEST = 599
    CHANGE_USERNAME = 600
    CHANGE_USER_VISIBLE_NAME = 610
    # CHANGE_USER_PFP = 620

    CHANGED_USERNAME = 602
    CHANGED_USER_VISIBLE_NAME = 612
    # CHANGE_USER_PFP_RESULT = 622

    ARE_U_ALIVE = 901
    I_AM_ALIVE = 900
    CLOSE = 1000


class LoginErrorCodes:
    SUCCESSFUL = 0
    BAD_REQUEST = 1
    INVALID_CREDENTIALS = 2
